{"uuid":"16a787e8-7686-413c-9dfb-c2886486f476","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["e1adfaad-9ea1-4bcf-a755-09e93dd8d540"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681611606597,"stop":1681611606598},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681611606941,"stop":1681611606942},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681611607060,"stop":1681611607061},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681611607139,"stop":1681611607140},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681611607160,"stop":1681611607160}],"start":1681611606431,"stop":1681611607160}