{"uuid":"193bc27e-a5a7-4814-bdd8-55ce34e1bb42","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["3c070dc3-d768-42f9-863c-ffc863e14375"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588739841,"stop":1681588739842},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588740068,"stop":1681588740068},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588740154,"stop":1681588740154},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588740214,"stop":1681588740214},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588740230,"stop":1681588740230}],"start":1681588739729,"stop":1681588740230}