{"uuid":"1f3db147-54b3-4cab-afbc-c4a95c73eec9","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["a17f6062-bc6b-42a8-9140-821937186e33"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609382558,"stop":1681609382559},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609382946,"stop":1681609382947},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609383068,"stop":1681609383068},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609383148,"stop":1681609383148},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609383172,"stop":1681609383172}],"start":1681609382366,"stop":1681609383173}