{"uuid":"23e9a73f-ad13-466b-a0d2-338da17fde04","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["af757e70-6d94-4110-a227-a92cd56465df"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608379407,"stop":1681608379409},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608379774,"stop":1681608379776},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608379921,"stop":1681608379921},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608380002,"stop":1681608380002},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608380026,"stop":1681608380027}],"start":1681608379251,"stop":1681608380027}