{"uuid":"3ecef70c-d522-4172-899b-13352084235e","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["3bca7b78-4375-4084-b347-e93e7a7a42d1"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681591275197,"stop":1681591275199},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681591275773,"stop":1681591275774},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681591275878,"stop":1681591275879},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681591275959,"stop":1681591275959},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681591275980,"stop":1681591275980}],"start":1681591275036,"stop":1681591275981}