{"uuid":"43262345-a18e-43fa-b8a7-1562cedb1d0b","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["23a8defb-e510-4315-b240-00bb69bef4f2"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681532853355,"stop":1681532853356},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681532854959,"stop":1681532854959},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681532855102,"stop":1681532855102},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681532855229,"stop":1681532855229},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681532855253,"stop":1681532855253}],"start":1681532853160,"stop":1681532855254}