{"uuid":"4824091c-e40d-4e72-b117-0b9fe857e5c2","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["ef7f139f-aa79-4668-9dc7-3270533f9bc0"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681587586725,"stop":1681587586727},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681587586985,"stop":1681587586986},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681587587073,"stop":1681587587073},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681587587137,"stop":1681587587138},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681587587165,"stop":1681587587167}],"start":1681587586609,"stop":1681587587169}