{"uuid":"518ccf50-4a79-4802-ae9a-dc0667598ca5","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["49b2ab59-c041-4e1a-9ad7-aecaad020f5d"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588661410,"stop":1681588661411},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588661648,"stop":1681588661649},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588666931,"stop":1681588666931},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588666992,"stop":1681588666993},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681588667013,"stop":1681588667014}],"start":1681588661272,"stop":1681588667014}