{"uuid":"56350a9e-8b48-4cf2-b346-92330d7264de","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["ce02e667-ac45-48fe-98e3-5d45ed839fc6"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681594011352,"stop":1681594011353},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681594014888,"stop":1681594014890},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681594015050,"stop":1681594015051},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681594015149,"stop":1681594015150},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681594015174,"stop":1681594015174}],"start":1681594011116,"stop":1681594015175}