{"uuid":"924cdd55-ff92-40f3-8936-8f023c9cd51f","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["84b09e89-17ef-4e7e-9cf3-ceb7235f0c7e"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681568502545,"stop":1681568502546},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681568504047,"stop":1681568504047},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681568504204,"stop":1681568504205},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681568504345,"stop":1681568504346},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681568504366,"stop":1681568504367}],"start":1681568502344,"stop":1681568504367}