{"uuid":"94b52e27-cc8d-4f08-b4e5-bd597f1c5392","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["ae17cffe-686a-4175-8702-c27f92831c75"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609055552,"stop":1681609055552},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609055898,"stop":1681609055899},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609056019,"stop":1681609056019},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609056103,"stop":1681609056104},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681609056148,"stop":1681609056148}],"start":1681609055374,"stop":1681609056148}