{"uuid":"ac25bed8-e290-47a9-b3ef-37bb1ea915c5","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["13e62048-cf2c-40e4-b2ce-19d3055a403c"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608832224,"stop":1681608832224},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608832694,"stop":1681608832695},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608832857,"stop":1681608832857},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608832960,"stop":1681608832961},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681608832996,"stop":1681608832996}],"start":1681608832035,"stop":1681608832997}