{"uuid":"f9aa4f64-e3f7-47fc-abac-3a7f141933ab","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["097ec3e2-eb4b-4197-9b93-6ae9f49d744b"],"befores":[],"afters":[{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681593460519,"stop":1681593460520},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681593460921,"stop":1681593460922},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681593461047,"stop":1681593461047},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681593461128,"stop":1681593461128},{"name":"hooks.Hook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1681593461148,"stop":1681593461148}],"start":1681593457173,"stop":1681593461149}